// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/header";
// import Footer from "@/components/footer";
// import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="es">
//     <body className={`antialiased min-h-screen`} >
//       {/* <Header /> */}
//       <main>
//         {children}
//       </main>
//       {/* <Footer /> */}
//       <Toaster position="top-center" richColors />
//     </body>
//   </html>

// );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Toaster } from "sonner";
import SessionWrapper from "@/components/SessionWrapper"; // 👈 nuevo

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`antialiased min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          {/* <Header /> */}
          <main>
            {children}
          </main>
          {/* <Footer /> */}
          <Toaster position="top-center" richColors />
        </SessionWrapper>
      </body>
    </html>
  );
}
