import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import SessionWrapper from "@/components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Osteodinamic",
  description: "Generated by create next app",
  manifest: "/manifest.json"
  //  manifest: "../../public/pwa/manifest.json"
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`antialiased min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          {/* <Header /> */}
          <main>
            {children}
          </main>
          {/* <Footer /> */}
          <Toaster position="top-center" richColors />
        </SessionWrapper>
      </body>
    </html>
  );
}